"""Static inventory of the Tableau workbooks (``*.twb``).

Parses the workbook XML (no Tableau installation needed) and reports data
connections, worksheets, dashboards and calculated fields, and flags
portability problems such as absolute file paths.

    python -m tools.inspect_workbooks            # print to stdout
    python -m tools.inspect_workbooks --write    # regenerate docs/workbook_inventory.md
    python -m tools.inspect_workbooks --check    # fail if the committed file is stale
"""

from __future__ import annotations

import argparse
import re
import sys
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List

from . import paths

OUTPUT = paths.DOCS_DIR / "workbook_inventory.md"
_UI_PLACEHOLDERS = {"Reset", "Reset2", "Reset_c", "Dummy"}


@dataclass
class Workbook:
    path: Path
    tableau_version: str
    source_build: str
    connections: List[Dict[str, str]] = field(default_factory=list)
    worksheets: List[str] = field(default_factory=list)
    dashboards: List[str] = field(default_factory=list)
    calculations: Dict[str, str] = field(default_factory=dict)
    uses_extract: bool = False

    @property
    def relative(self) -> str:
        return self.path.relative_to(paths.REPO_ROOT).as_posix()

    @property
    def absolute_paths(self) -> List[str]:
        found = []
        for conn in self.connections:
            for key in ("directory", "filename", "dbname"):
                value = conn.get(key, "")
                if value.startswith("/") or re.match(r"^[A-Za-z]:[\\/]", value):
                    found.append(value)
        return sorted(set(found))


def _clean_formula(formula: str) -> str:
    return " ".join(formula.split())


def parse(path: Path) -> Workbook:
    root = ET.parse(path).getroot()
    workbook = Workbook(
        path=path,
        tableau_version=root.get("version", ""),
        source_build=root.get("source-build", ""),
    )
    seen = set()
    for conn in root.iter("connection"):
        cls = conn.get("class", "")
        if cls in {"federated"}:
            continue
        if cls == "hyper":
            workbook.uses_extract = True
        keys = ("class", "dbname") if cls == "hyper" else ("class", "directory", "filename")
        entry = {k: conn.get(k, "") for k in keys if conn.get(k)}
        key = tuple(sorted(entry.items()))
        if key not in seen:
            seen.add(key)
            workbook.connections.append(entry)
    workbook.worksheets = sorted({ws.get("name") for ws in root.iter("worksheet")})
    workbook.dashboards = sorted({db.get("name") for db in root.iter("dashboard")})
    for column in root.iter("column"):
        calc = column.find("calculation")
        if calc is None or not calc.get("formula"):
            continue
        name = (column.get("caption") or column.get("name", "")).strip("[]")
        if name.endswith("(bin)") or name in _UI_PLACEHOLDERS:
            continue
        workbook.calculations.setdefault(name, _clean_formula(calc.get("formula")))
    return workbook


def discover() -> List[Workbook]:
    return [parse(p) for p in sorted(paths.REPO_ROOT.glob("0*/*.twb"))]


def _md_escape(text: str) -> str:
    return text.replace("|", "\\|")


def _shorten(formula: str, limit: int = 160) -> str:
    return formula if len(formula) <= limit else formula[: limit - 3] + "..."


def render(workbooks: List[Workbook]) -> str:
    lines = [
        "# Workbook Inventory",
        "",
        "<!-- Generated by `python -m tools.inspect_workbooks --write`. Do not edit by hand. -->",
        "",
        "Static inventory of every Tableau workbook in the repository, extracted from the",
        "workbook XML. Use it to review calculated-field logic without opening Tableau.",
        "",
        "## Summary",
        "",
        "| Workbook | Tableau | Data source | Extract | Worksheets | Dashboards | Absolute paths |",
        "|---|---|---|---|---:|---:|---|",
    ]
    for wb in workbooks:
        source = ", ".join(sorted({c["class"] for c in wb.connections}))
        lines.append(
            f"| `{wb.relative}` | {wb.tableau_version} | {source} | {'yes' if wb.uses_extract else 'no'} "
            f"| {len(wb.worksheets)} | {len(wb.dashboards)} | {'**yes**' if wb.absolute_paths else 'no'} |"
        )
    lines += [
        "",
        "Workbooks marked **yes** under *Absolute paths* point at files on the author's",
        "machine: the raw data in a downloads folder and, where *Extract* is yes, a",
        "Tableau `.hyper` extract that is not distributed with this repository. On",
        "another machine Tableau Desktop will prompt for the file. Use *Data > Edit Data",
        "Source* (or *Edit Connection*), select the file in the project's `Dataset/`",
        "folder, and refresh or recreate the extract.",
        "",
    ]
    by_project: Dict[str, List[Workbook]] = {}
    for wb in workbooks:
        by_project.setdefault(wb.relative.split("/")[0], []).append(wb)
    for project, items in by_project.items():
        lines += [f"## {project}", ""]
        for wb in items:
            lines += [f"### `{wb.path.name}`", ""]
            lines.append(f"- **Build:** {wb.source_build}")
            for conn in wb.connections:
                described = ", ".join(f"{k}=`{v}`" for k, v in conn.items())
                lines.append(f"- **Connection:** {described}")
            lines.append(f"- **Dashboards:** {', '.join(f'`{d}`' for d in wb.dashboards) or 'none'}")
            lines.append(f"- **Worksheets:** {', '.join(f'`{w}`' for w in wb.worksheets)}")
            lines.append("")
        # Calculated fields are identical across a project's workbooks; list once.
        calcs: Dict[str, str] = {}
        for wb in items:
            for name, formula in wb.calculations.items():
                calcs.setdefault(name, formula)
        lines += ["#### Calculated fields", "", "| Field | Formula |", "|---|---|"]
        for name in sorted(calcs, key=str.lower):
            lines.append(f"| `{_md_escape(name)}` | `{_md_escape(_shorten(calcs[name]))}` |")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main(argv: List[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help=f"write {OUTPUT.relative_to(paths.REPO_ROOT)}")
    mode.add_argument("--check", action="store_true", help="exit 1 if the committed inventory is stale")
    args = parser.parse_args(argv)

    text = render(discover())
    if args.write:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(text, encoding="utf-8")
        print(f"wrote {OUTPUT.relative_to(paths.REPO_ROOT)}")
    elif args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != text:
            print(f"{OUTPUT.relative_to(paths.REPO_ROOT)} is stale; run `python -m tools.inspect_workbooks --write`.")
            return 1
        print(f"{OUTPUT.relative_to(paths.REPO_ROOT)} is up to date.")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
